### ISSUE TITLE
Documentation link for Language Identification needs updating

### ISSUE THREAD

**Issue by djhunt** [watson-developer-cloud/node-red-node-watson#139]
Returns a 404.  Should it be: http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/language-translation/api/v2/#identify

**Comment by chughts** [comment]
The link to the documentation should actually be https://www.ibm.com/watson/developercloud/language-translation.html
This might be a little confusing as the language identification service was merged into language-translation. The 404 will be corrected in the next code drop.

**Comment by chughts** [comment]
Fixed in #141
