### ISSUE TITLE
Missing Alchemy API service credentials

### ISSUE THREAD

**Issue by jeancarl** [watson-developer-cloud/node-red-node-watson#140]
Reproduce:
1) Create Node-RED app with name of alchemynodered
2) Bind Alchemy service into application
3) Add Feature Extract node

Error:
Node-RED recognizes bound Alchemy service, but errors out with "Missing Alchemy API service credentials".

Bug:
Seems VCAP services finds Cloudant service (named alchemynodered-first, matching on line 55:

var service = cfenv.getAppEnv().getServiceCreds(/alchemy/i);

https://github.com/watson-developer-cloud/node-red-node-watson/blob/master/services/alchemy_language/v1.js#L55

Looks like alchemy-vision node is also affected.

**Comment by chughts** [comment]
This is a feature of the cfenv npm module, which is used to fetch service credentials. In the case of your example the call to getServiceCreds is matching against the auto-generated name for the Cloudant service. We can make the search for the service more exact, for the case for Alchemy Language - 'alchemy_api', so the restriction will become that you don't use 'alchemy_api' in your application name.

**Comment by chughts** [comment]
Fixed in #235 for Feature Extract and Date Detection, will be in release 0.4.33
