### ISSUE TITLE
Can't add/bind a Visual Recognition service to node-red.

### ISSUE THREAD

**Issue by joe4k** [watson-developer-cloud/node-red-node-watson#143]
<img width="448" alt="screen shot 2016-07-05 at 9 49 58 am" src="https://cloud.githubusercontent.com/assets/7071435/16590233/bbfa6196-42a4-11e6-8a95-397e8236f571.png">

Is anyone able to add/bind VR service to node-red application?

**Comment by chughts** [comment]
This is a feature of the V3 Visual Recognition service. You are only allowed one key, even when you are binding in an existing service tile into any application, an attempt is made to allocate a new key which will always fail. 

If you have an instance of the service bound into any other application, then use it unbound with node-RED. If you don't have another instance then you will be ok. You will need to delete all instances that you have created. Wait 24 hours. Then create / bind (in one action) into your node-RED instance.

**Comment by chughts** [comment]
Fixed in #149. Single key issue remains, but automatic binding was looking at apikey, when it should have been looking for api_key. Fix will be in 0.4.6
