### ISSUE TITLE
Feature Extract no longer works with URLs

### ISSUE THREAD

**Issue by jeancarl** [watson-developer-cloud/node-red-node-watson#144]
Passing a URL to the Alchemy Feature Extract node no longer analyzes the contents at the given URL. It used to fetch and analyze the content.

Need to change params.text property to be a params.url property if a URL is passed in?
https://github.com/watson-developer-cloud/node-red-node-watson/blob/master/services/alchemy_language/v1.js#L113

FLOW:
[{"id":"f92853fe.bc3308","type":"alchemy-feature-extract","z":"233260a0.9542f8","name":"","page-image":"","image-kw":"","feed":"","entity":true,"keyword":true,"title":"","author":"","taxonomy":"","concept":"","relation":"","pub-date":"","doc-sentiment":"","doc-emotion":"","x":377.5,"y":44.25,"wires":[["87db064d.6136f8"]]},{"id":"838ac5cd.8b0b","type":"inject","z":"233260a0.9542f8","name":"","topic":"","payload":"https://techcrunch.com/2016/07/05/drivers-are-warming-up-to-autonomous-cars-mostly/","payloadType":"str","repeat":"","crontab":"","once":false,"x":201.5,"y":43.25,"wires":[["f92853fe.bc3308"]]},{"id":"87db064d.6136f8","type":"debug","z":"233260a0.9542f8","name":"","active":true,"console":"false","complete":"true","x":545.5,"y":46.5,"wires":[]}]

RESULT:
msg : Object{ "topic": "", "payload": "https://techcrunch.com/2016/07/05/drivers-are-warming-up-to-autonomous-cars-mostly/", "_msgid": "c1fe8041.3e018", "features": { "page-image": {}, "image-kw": {}, "feed": {}, "entity": [], "keyword": [], "title": {}, "author": {}, "taxonomy": {}, "concept": {}, "relation": {}, "pub-date": {}, "doc-sentiment": {}, "doc-emotion": {} } }

**Comment by chughts** [comment]
fixed in #145  will be released in 0.4.6
