### ISSUE TITLE
Missing Watson Visual Recognition API service credentials

### ISSUE THREAD

**Issue by jeancarl** [watson-developer-cloud/node-red-node-watson#147]
Looks like VCAP services changed the apikey property to api_key. Node-RED fails to automatically find the apikey property and displays the following error in debug pane:

Missing Watson Visual Recognition API service credentials

Credential JSON:
"credentials": {
        "url": "https://gateway-a.watsonplatform.net/visual-recognition/api",
        "note": "It may take up to 5 minutes for this key to become active. This is your previously active free apikey. If you want a different one, please wait 24 hours after unbinding the key and try again.",
        "api_key": "01010101010101010101010101010101"
    }

FIX:

https://github.com/watson-developer-cloud/node-red-node-watson/blob/master/services/visual_recognition/v3.js#L34

if (service) {
  sAPIKey = service.api_key;
}

**Comment by chughts** [comment]
Fixed in #149 will be released in 0.4.6
