### ISSUE TITLE
Conversation Node No Longer Works with GA Release

### ISSUE THREAD

**Issue by sharpstef** [watson-developer-cloud/node-red-node-watson#148]
Conversation literally just went GA so this is more a timing nastiness, but had some users trying to hack with it in Node-RED so figured I'd note the update. The connection parameters no longer work.

Change:
`node.service = watson.conversation({
      username: userName,
      password: passWord,
      version_date: '2016-05-19',
      version: 'v1-experimental'
    });`

To:
`node.service = watson.conversation({
      username: userName,
      password: passWord,
      version: 'v1',
      version_date: '2016-07-11'
    });`

**Comment by chughts** [comment]
Fixed in #150 will be released in 0.4.6
