### ISSUE TITLE
Retrieve and Rank Search and Rank node only takes default "fl" params

### ISSUE THREAD

**Issue by yeeyaa** [watson-developer-cloud/node-red-node-watson#163]
It would be better if we could be able to let the node accept user defined params to make this node more useful.

**Comment by DanCunnington** [comment]
hi @yeeyaa - thanks for your suggestion. Would the ability to pass in the cluster id, collection name and ranker id be sufficient? I can configure the node to accept msg.cluster_id, msg.collection_name and msg.ranker_id

**Comment by DanCunnington** [comment]
@chughts - I'll also look at implementing this for the other nodes, it makes sense to allow parameters to be passed on the msg object. It will make life easier for combining nodes

**Comment by DanCunnington** [comment]
@yeeyaa - Going to close this issue, feel free to reopen if you have any problems. Thanks
