### ISSUE TITLE
Visual recognition ignores 'Accept-Language' parameter

### ISSUE THREAD

**Issue by jaumemir** [watson-developer-cloud/node-red-node-watson#167]
Assuming Visual Recognition reference API is:
https://watson-api-explorer.mybluemix.net/apis/visual-recognition-v3#!/visual-recognition/get_v3_classify

The node-red module implementation does not implement msg.params["Accept-Language"] = "es", which is supported by the API.

**Comment by chughts** [comment]
Fixed in #171, incorporated into release 0.4.9
