### ISSUE TITLE
Not able to fetch document content using Retrieve and Rank Service

### ISSUE THREAD

**Issue by ruchi2912** [watson-developer-cloud/node-red-node-watson#175]
Hi ,
I have trained ranker. When i am trying to use R&R Node in Nodered , I am not able to fetch the content of documents. It is only returning document id and title.

**Comment by chughts** [comment]
Fixed in #178 
Will be released in 0.4.10

**Comment by chughts** [comment]
0.4.10 has been released.

**Comment by ruchi2912** [comment]
Thanks for update!
