### ISSUE TITLE
update README with installation instructions and dependencies

### ISSUE THREAD

**Issue by emigenix** [watson-developer-cloud/node-red-node-watson#187]
Please update README with installation instructions and dependencies. It would also be useful with some links to example usage where the nodes are used in context.

**Comment by chughts** [comment]
These are nodes to be used with node-RED. To use them you have to have node-RED. If you are using node-RED on Bluemix then you already have them installed, and each node has its own information page. If you are running node-RED outside of Bluemix, then you will already have good idea of how to install additional nodes. If not there is documentation on the node-RED org page describing the process http://nodered.org/docs/getting-started/adding-nodes

If you are looking for sample flows then they are here - https://github.com/watson-developer-cloud/node-red-labs

If you want to contribute code then our contributing documentation describes how to set up your development environment. https://github.com/watson-developer-cloud/node-red-node-watson/blob/master/CONTRIBUTING.md

**Comment by emigenix** [comment]
Hi @chughts,
- [x] These are nodes to be used with node-RED. 
- [x] To use them you have to have node-RED. 
- [x] If you are using node-RED on Bluemix then you already have them installed,
- [ ] ...and each node has its own information page. 
- This info is incomplete for `node-red-node-watson` as it only refer back to this page. 
- [x] If you are running node-RED outside of Bluemix, then you will already have good idea of how to install additional nodes. 
- Yep, but it doesn't say how to install additional nodes when using node-red on Bluemix. At least I can't find it!
- [ ] **N/A!** If not there is documentation on the node-RED org page describing the process http://nodered.org/docs/getting-started/adding-nodes
- Not applicable. It doesn't say anything about how to install nodes in the Bluemix cloud environment.
- [x] If you are looking for sample flows then they are here - https://github.com/watson-developer-cloud/node-red-labs
- [x] If you want to contribute code then our contributing documentation describes how to set up your development environment. https://github.com/watson-developer-cloud/node-red-node-watson/blob/master/CONTRIBUTING.md

At the end of the day, even writing what you just wrote above, in the README would be more helpful than as it is presented now.
