### ISSUE TITLE
Node-RED not up to date with Bluemix/Watson IoT

### ISSUE THREAD

**Issue by andylapping** [watson-developer-cloud/node-red-node-watson#204]
It seems that Node-RED on Bluemix is not leeping up to date with changes in Bluemix / IoT Platform. 

I havent done an extensive test yet but so far:

Language Translator (the new one not the deprecated Watson Translation) - does not bind autonatically to Node-RED (although you can generate service credentials and manually copy and paste them in)

Visual Recognition - does not bind automatically and provides no option to manually enter a key

Speech to Text - binds ok but when you feed it a binary it chokes on it (this is a regression as it was working fine a couple of weeks ago)

**Comment by chughts** [comment]
We are working on the translator nodes, and hope to release them this week. For now the translation nodes and service are still available and will work.

**Comment by andylapping** [comment]
Thanks ! The Translator nodes do work if you manually give them credentials. 
Any ideas about the Visual Recognition / Speech to Text nodes ?

**Comment by chughts** [comment]
@skilganon this is not the right forum for this line of questions. Please raise this question on developerworks forum, and we will answer. I will leave this request open so we can feedback on the translator nodes when they are ready.

**Comment by andylapping** [comment]
Apologies - the DW Open Slack channel advised I post the request here - I've posted to the DW forum too - I'll switch to that one.

**Comment by chughts** [comment]
Thanks

**Comment by chughts** [comment]
Language Translator nodes created in release 0.4.19
