### ISSUE TITLE
Conversation params.alternate_intents not working

### ISSUE THREAD

**Issue by dschindl** [watson-developer-cloud/node-red-node-watson#218]
I'm getting error when using the params.alternate_intents in Node Red using conversation node

**Comment by chughts** [comment]
What is the error that you are getting?

**Comment by dschindl** [comment]
It says: "call to watson conversation services failed".

2016-11-15 10:44 GMT-03:00 Soheel Chughtai notifications@github.com:

**Comment by chughts** [comment]
And by not specifying params.alternate_intents it works?

**Comment by dschindl** [comment]
Yes, if I don't specify then it works fine

2016-11-15 12:38 GMT-03:00 Soheel Chughtai notifications@github.com:

**Comment by chughts** [comment]
We are investigating.

**Comment by chughts** [comment]
I have just tried with

```
msg.params = {};
msg.params.alternate_intents = true;
return msg;
```

and that is working, with the alternative intents returned as expected.
How are you specifying msg.params.alternate_intents ?

**Comment by dschindl** [comment]
I was specifying with a "template" node.
Like this:
[image: Imágenes integradas 1]

2016-11-15 14:06 GMT-03:00 Soheel Chughtai notifications@github.com:

**Comment by chughts** [comment]
I can't see your image. I am closing this issue as a user error.

In future please raise questions like this on developerworks answers, where the question and answer will get wider visibility. If we think it is a code problem, then we will direct to this repository.
