### ISSUE TITLE
Loaded 15.2 node-red and Watson conversation service no longer as username password fields to config

### ISSUE THREAD

**Issue by dennisnotojr** [watson-developer-cloud/node-red-node-watson#222]
Testing the latest node-red, watson nodes, etc. Noticed that all watson services have username and password but watson conversation service only has workspace_id? How do you set the username/password for the service?  Works find in my 14.4 build, and 15.1 build of node-red. 

Thanks, Den

**Comment by chughts** [comment]
All the Nodes work the same, they all ask for credentials, unless the credentials are automatically found because the service is bound to the node-red application.

**Comment by dennisnotojr** [comment]
Dude, that does not address the problem.  you can not put in the credentials to the watson conversation service which the latest release.  This is a bug! Picture attached. Username and password fields are gone!  

![wcs](https://cloud.githubusercontent.com/assets/6285300/20712811/f37ed21a-b602-11e6-8452-e2b948955acb.jpg)

**Comment by dennisnotojr** [comment]
All other watson nodes have the username/password fields. Please fix immediately or route to the ones can address.

**Comment by dennisnotojr** [comment]
Here's what it looked like in the 15.1 release of node-red which is correct.
![wcs2](https://cloud.githubusercontent.com/assets/6285300/20712942/9b0cdafe-b603-11e6-9ec8-0884a6fe2d0c.jpg)

**Comment by chughts** [comment]
This is a Bluemix instance that I created today, and didn't bind in Conversation.

<img width="511" alt="screen shot 2016-11-29 at 14 14 21" src="https://cloud.githubusercontent.com/assets/10371360/20712986/6db160bc-b63e-11e6-9df2-684a56291c68.png">

**Comment by chughts** [comment]
What is the name of your Node-RED application?

**Comment by dennisnotojr** [comment]
could this be an issue with the boiler plate Node-Red Starter title. That is what I used to create my new instance?  Doesn't make any sense.

**Comment by dennisnotojr** [comment]
Try it yourself.

**Comment by chughts** [comment]
Most likely to be related to the name of your node-red instance. The cloudant database that gets created will match that name. That means that when the vcap module looks for the conversation setting it finds the cloudant one. This is a known problem with all the services, not just conversation.

**Comment by dennisnotojr** [comment]
Let me try a different name

**Comment by dennisnotojr** [comment]
can the app name and host name be the same?

**Comment by chughts** [comment]
App name and host name can be the same.

**Comment by dennisnotojr** [comment]
Well your hunch was correct. Used a different name and the username/password is now present.

Weird - the name I used before "UCG" didn't work, but "NodeRed-V3" did?  Hmm.
