### ISSUE TITLE
STT Customisation and Custom Corpora Methods

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-red-node-watson#226]
The Node-SDK now supports the STT Customisation and Custom Corpora methods. Equivalents for the node-RED node need to created.

**Comment by chughts** [comment]
We have an urgent request to implement this feature asap. I am investigating whether to incorporate all features into the current node, or to have a new STT Customisation node for the corpus training and only add the customisation selection only to the existing node.

**Comment by ALBALTAR** [comment]
Great! that will be very helpful.

**Comment by arla916** [comment]
I believe that the request was to add the ability to USE a custom model in a recognition request and NOT to create the custom model using Node Red.  It should be a lot less work to allow passing a customization_id in the recognize request.  Albaltar, please confirm.

**Comment by chughts** [comment]
I agree, but it doesn't look as though implementing the custom model creation will be too difficult with a new mode for STT Custom Model creation. I will aim to get the new node developed this weekend and published on Monday. If I can't get the custom node created by that timeframe I will release the existing node with the extra custom id option.

**Comment by arla916** [comment]
Sounds good!  Thanks.

**Comment by ALBALTAR** [comment]
Sounds great!!! THANKS.
Alberto Baltar
IBM Associate Partner
Móvil: +34 629077840
alberto.baltar@es.ibm.com

**Comment by ALBALTAR** [comment]
The need is to add the Customization ID parameter in the current STT box.

**Comment by chughts** [comment]
No, that is your need. I own the nodes, and my need is to implement the full service.

**Comment by ALBALTAR** [comment]
If you develop a new node it is also Ok for me. Thanks

**Comment by chughts** [comment]
New STT Customisation Node created in #241 which implements the create customisation and corpora  methods. STT node now allows customisation id to be specified. Code has been published as version 0.4.36

Word training has yet to be added. Keeping this enhancement request open until word training is implemented.

**Comment by chughts** [comment]
Words training added and released in 0.4.37

**Comment by ALBALTAR** [comment]
thanks.

**Comment by ALBALTAR** [comment]
Hi, I see a new node for Building Customized conversations. those customized comversations generate a CustomizationID that must be introduced as a parameter in the STT API. Where can I do that?

Thanks

**Comment by chughts** [comment]
A customization ID selection field shows up, if you select a model for which there is at least one customization available. If you select a model for which there is no customisation then the selection field does not show.

**Comment by SetaSouto** [comment]
Hi, I find a bug (I think) or at least an improvement that could be done to the node STT. I was using the node to listen to Spanish voices, so then I wanted to create a custom model, add a *corpora* and use the custom model. But when I came back to the node STT, it did not have the option to select the language customization. So, to find the customization, I was forced to restart the app and then it appears. It could be a good option to inspect or at least add that to the documentation of the node in node-red.

**Comment by chughts** [comment]
@SetaSouto please raise this as a separate issue.
