### ISSUE TITLE
Sentiment for keywords and entities

### ISSUE THREAD

**Issue by vhrtanek** [watson-developer-cloud/node-red-node-watson#234]
JSON generated by Alchemy API is able to offer sentiment for keywords and entities. Would it be possible to enable this option in Feature Extract node?

**Comment by chughts** [comment]
The Node uses the Combined Call, but it looks like targeted emotion is available for keywords and entities by setting emotion=1. Documentation doesn't mention it but we can try also setting sentiment=1, to see if keyword & entity sentiment is returned. 

Will need to carry out some tests, to verify if this is possible.

**Comment by chughts** [comment]
Fixed in #237 will be released in 0.4.34
