### ISSUE TITLE
Need to change user name and password on Conversation as a msg parameter

### ISSUE THREAD

**Issue by chrispw0** [watson-developer-cloud/node-red-node-watson#236]
Please can we have the ability to change the user name/password by passing parameters on the msg.

**Comment by chughts** [comment]
Which node would you want to do this on?

Some of the nodes make use of the credentials to populate the configuration dialog, so this would not be possible in the discovery, language translation, speech to text and text to speech nodes.

**Comment by chrispw0** [comment]
Only on conversation 

Chris Williams
Chief Architect -  Europe
IBM Watson

**Comment by chughts** [comment]
Implemented in #238. Will be released in 0.4.34
