### ISSUE TITLE
alchemy API docs rehomed

### ISSUE THREAD

**Issue by ibmrcruicks** [watson-developer-cloud/node-red-node-watson#249]
references to alchemyAPI docs should now point to 
https://www.ibm.com/watson/developercloud/dashboard/en/alchemyapi-dashboard.html

https://alchemyapi.readme.io/ no longer valid

**Comment by arlemi** [comment]
Where did you see a link to the documentation? Was it this repository or the [node-red-labs](https://github.com/watson-developer-cloud/node-red-labs) one?

**Comment by chughts** [comment]
The info for the node points at http://www.alchemyapi.com/api, which redirects to https://www.ibm.com/watson/developercloud/doc/index.html.

We can update the info to use the redirect page.

**Comment by ibmrcruicks** [comment]
node-red-node-watson - /services/alchemy_data_news/v1.html still contains the readme.io reference

**Comment by chughts** [comment]
Looks like 2 nodes that need updating. @arlemi are you planning to make the update?

**Comment by arlemi** [comment]
I'll update the link and make a PR. Thanks @ibmrcruicks 

@chughts which other node would need updating?

**Comment by chughts** [comment]
Alchemy News, and Alchemy Language. Alchemy News has the link that @ibmrcruicks mentions and Alchemy Language has the redirected url.

**Comment by chughts** [comment]
Completed by @arlemi will be bundled in next release.
