### ISSUE TITLE
Alchemy API Node Red doesn't print out the pub-date

### ISSUE THREAD

**Issue by ghost** [watson-developer-cloud/node-red-node-watson#252]
In the Node-Red, the alchemy api module does not produce some values which are extracted in the alchemy api demo & alchemy explorer. I tested the url 'http://www.ibm.com/us-en/'.

**The weired output is**

msg.features["pub-date"] : Object
{ empty }

**but in the demo & explorer the output is** 
{
  "status": "OK",
  "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
  "url": "http://www.ibm.com/us-en/",
  "totalTransactions": "1",
  "language": "english",
  "publicationDate": {
    "confident": "yes",
    "date": "20151001T000000"
  }

**Comment by chughts** [comment]
Just ran it and got the following output - 

```
msg : Object
  object
    _msgid: "7cff3c00.8300c4"
    topic: ""
    payload: "http://www.ibm.com/us-en/"
    features: object
      page-image: object
      image-kw: object
      feed: object
      entity: array[11]
      keyword: array[30]
      title: object
      author: object
      taxonomy: object
      concept: object
      relation: object
      pub-date: object
        date: "20151001T000000"
        confident: "yes"
      doc-sentiment: object
      doc-emotion: object
```

If you are still seeing problems then please raise a question on DeveloperWorks answers where we will help you as much as we can.
