### ISSUE TITLE
NLU doesn't have configuration (model and language) like Alchemy

### ISSUE THREAD

**Issue by gustavomr** [watson-developer-cloud/node-red-node-watson#268]
Hi, using Alchemy is possible to configure parameters like model and language through:

msg.alchemy_options = {
     language: "portuguese",
    model: "xxxxxxxxxxxxxxxxxxxxxxxx"
};

How can I do with NLU? Is it a feature request?

**Comment by chughts** [comment]
Agree, we need to add the equivalent for Natural Language Understanding.

**Comment by jaumemir** [comment]
It is specially critical to be able to fix the language **at configuration level**, when the service is used to analyze short texts always from same language. When text is too short for the service to identify the language, it leads to errors.

**Comment by chughts** [comment]
@Repjarms do you have a progress checkpoint?

**Comment by chughts** [comment]
Implemented and will be released in 0.5.5 
- Natural Language Understanding Node now allows language and model overrides on 
msg.nlu_options.language, msg.nlu_options.entity_model and msg.nlu_options.relations_model.

**Comment by chughts** [comment]
V 0.5.5 Released.
