### ISSUE TITLE
Document Conversion Node not Binding

### ISSUE THREAD

**Issue by andylapping** [watson-developer-cloud/node-red-node-watson#272]
On Bluemix - I have a Node-RED Flow trying to use Document Conversion. Despite the app being bound to the doc conversion service - it does not appear in the node. If i try manually to insert credentials that doesnt work either. I can access the same service programmatically using Java outside of Bluemix so its an issue with the Node-RED Node. I've tried unbinding and rebinding and restarting. I have a support ticket open but they cannot figure out why its not working either.

**Comment by chughts** [comment]
Please raise this as a question on developerworks answers. where there will be greater visibility and where I will help you out as much as I can. 

If in our discussion we determine that there is a code bug then we set this issue as a defect and fix, but until then I do not answer usage question in this repo.
