### ISSUE TITLE
Move trade off analytics to the deprecated list

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-red-node-watson#276]
As per the notice - The IBM Watson™ Tradeoff Analytics service is being deprecated. As of May 11, 2017, it will no longer be possible to create a new instance of the service on Bluemix. Existing service instances will continue to be supported until April 11, 2018.

**Comment by chughts** [comment]
Node will be moved to deprecated list in release 0.5.5

**Comment by chughts** [comment]
V 0.5.5 Released.

**Comment by dawangandypeng** [comment]
is there any replacement for this service? what is the solution for those who have implemented this project?

**Comment by chughts** [comment]
This is not the right place to ask this question. Either raise a ticket on Bluemix, or ask the question on a forum like DeveloperWorks Answers
