### ISSUE TITLE
Conversation Node - Can't send empty payload

### ISSUE THREAD

**Issue by fgallinari** [watson-developer-cloud/node-red-node-watson#298]
Conversation should be able to receive empty messages, but the way the node-red conversation node is developed, it throws an error:

<img width="236" alt="captura de tela 2017-05-28 as 22 34 09" src="https://cloud.githubusercontent.com/assets/6473638/26533966/d5d2fff8-43f5-11e7-9262-878eb801f0ce.png">

This way, I cannot use the conversation_start trigger inside Watson Conversation dialog.

**Comment by chughts** [comment]
I do not answer usage questions here. Please raise this question on developerworks answers, where it will be answered.

**Comment by fgallinari** [comment]
I believe you did not understand, but you have a bug in your code.

On line 34, you check:
`34: if (!msg.payload)`
But you are mistaken to think that on line 104, you can't have `{text: ""};`
`104: params.input = {text:msg.payload};`

Anyway, I've just seen that you are using an outdated version of conversation service, so it's probably better to avoid using this node.


Thanks!

Regards,

**Comment by chughts** [comment]
Updating the version date I can accept as a request. Payload isn't because the way to trigger conversation_start is to reset the context and not send an empty message.
