### ISSUE TITLE
Watson Visual Recognition parameter to select "classify", "faces" or "text"

### ISSUE THREAD

**Issue by johnwalicki** [watson-developer-cloud/node-red-node-watson#303]
I've got a requirement for a Watson Visual Recognition setting 
msg.params.detect_mode = ["classify","text","faces"]
I could simplify several flows if I could pass in whether I wanted the Visual Recognition node to attempt to Classify an Image, Detect Faces or Recognize Text.  I might want to take multiple passes to classify an image, get the text and detect the face.

**Comment by chughts** [comment]
Implemented in release 0.5.10

**Comment by johnwalicki** [comment]
Thanks - I wrote a test case Node-RED flow that uses the node-red-node-watson 0.5.10 and the new Watson Visual Recognition node that supports msg.params.detect_mode.   My test case was successful.  I was able to use the same photo and have a single Watson Visual Recognition node do image classification, face detection and text extraction depending on which msg.params I passed it.
