### ISSUE TITLE
Personality Insights node could not work in Japanese mode.

### ISSUE THREAD

**Issue by prismboy** [watson-developer-cloud/node-red-node-watson#315]
I set "Japanese" to "Input Text Language" option, and run the flow.
But the node couldn't work. Node.js runtime was down.

So, I changed language option to "English" and deploy the flow.
Then the node worked.

**Comment by chughts** [comment]
Please raise this as a question on developerworks answers. If in the course of answering we determine it's a bug then we will reopen this issue.
