### ISSUE TITLE
conversation workspace manager node 

### ISSUE THREAD

**Issue by dennisnotojr** [watson-developer-cloud/node-red-node-watson#317]
Missing the dialog node api calls:

List dialog nodes
Create dialog node
Delete dialog node
Get dialog node
Update dialog node

https://www.ibm.com/watson/developercloud/conversation/api/v1/?node#dialog_nodes

**Comment by chughts** [comment]
Implemented in 0.5.17, awaiting release.

**Comment by chughts** [comment]
Published.
