### ISSUE TITLE
Need to be able to set the url for Watson nodes - US, Germany, etc

### ISSUE THREAD

**Issue by dennisnotojr** [watson-developer-cloud/node-red-node-watson#318]
I would like to pass the url for germany bluemix to watson conversation service
url": "https://gateway-fra.watsonplatform.net/conversation/api"

also would like it for all the rest of the watson nodes??

Den

**Comment by chughts** [comment]
This has already been implemented as of version 0.5.9

**Comment by dennisnotojr** [comment]
How? setting the msg.url doesn't work. I have 0.5.11 nodered-watson-nodes installed. Do not see an endpoint param in watson conversation service.

**Comment by dennisnotojr** [comment]
I'm dumb, found it. please close
