### ISSUE TITLE
Internet Explorer won't load all of Node-RED after installing watson nodes.  Recreate provided.

### ISSUE THREAD

**Issue by hthomann** [watson-developer-cloud/node-red-node-watson#352]
HI!  I sometimes notice that Node-RED (NR) won't load in Internet Explorer (IE).  If I use Firefox or Edge, it does load.  It seems to only happen for IE.  Maybe it is something unique to my install?  I seem to have found a scenario where, using node-red-node-watson, NR will not load in IE.  Please take the following scenario:

1) Bring up NR editor in IE.
2) Install node-red-node-watson via the manage palette menu option.
3) View the palette and notice that all watson nodes are visible after the install.  Given this, all seems to be installed correctly.
4) Refresh/reload the NR editor in IE, and notice that the palette and flows won't load.  Basically only the "frames" of NR load.  
5) Go to the menu (luckily, enough of NR loads such that the menu is still accessible).
6) Select the manage palette option.
7) Find node-red-node-watson and select the option to disable all node-red-node-watson nodes.  NOTE: if you placed any of the watson nodes in a flow, the disable option will not be available since watson nodes are in use. 
8) Refresh/reload the browser and now the NR editor loads in IE.
9) I'm only interested in the tone node, so I go back to the node-red-node-watson in manage palette and enable only the tone node.
10) Refresh the browser and NR still loads in IE, and I have the tone node I want.

Please let me know if you have any questions.  I feel like, but could be wrong, I've seen issues where IE fails to fully load NR before I was using the node-red-node-watson, so maybe this issue isn't unique to node-red-node-watson?  

Thanks,

Heath Thomann

**Comment by chughts** [comment]
If you get the same problem without installing the Watson nodes, then the problem does not relate directly to these nodes. It appears to be IE. related. I would advise you not to use IE. but you should raise this as a question on the Node-RED google groups forum - https://groups.google.com/forum/#!forum/node-red
