### ISSUE TITLE
visual recognition Can't Detect Faces

### ISSUE THREAD

**Issue by kent1026** [watson-developer-cloud/node-red-node-watson#359]
"Classify an image" and "Recognize Text" is work
but "Detect Faces" print : "invalid-api-key"

**Comment by chughts** [comment]
I have just tried this, and it is working. I suggest that you have a flow error, in which case I am closing this issue, and will request that you raise a question on DeveloperWorks Answers where you we will be happy to help you resolve your invalid key problem.
