### ISSUE TITLE
Visual Recognition only English results

### ISSUE THREAD

**Issue by hmd83** [watson-developer-cloud/node-red-node-watson#363]
Hallo 
Visual Recognition only giving  English results in calssfiy  0.6.1  but in 0.5.23 work fine with Arabic and if you can add german 
Thanks 
node red 0.17.5 raspberry pi

**Comment by chughts** [comment]
This was due to the underlying watson-developer-cloud fixing how the API accepted Accept-Language. 

The node has been fixed and will be packaged into 0.6.2

**Comment by chughts** [comment]
Fixed in 0.6.2
