### ISSUE TITLE
Remove references to Language Translation

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-red-node-watson#372]
### Acceptance Criteria

- [ ] Should not mention Language Translation unless it's a deprecation notice
- [ ] Should not have code that sends requests to `language-translation`

**Comment by germanattanasio** [comment]
The service name belongs to a company in Europe so we were advised by the IBM Legal team to remove all the references to that service. We should use Language Translator

**Comment by chughts** [comment]
Completed - Will be included in release 0.6.3
