### ISSUE TITLE
Language Identification node only outputs the primary language

### ISSUE THREAD

**Issue by PaulRead** [watson-developer-cloud/node-red-node-watson#380]
The Language identification node used to provide:
* msg.lang the primary language and 
* msg.languages  an array of identified languages

However now the msg.languages appears to be empty, I do not get an error if I try to show it but there is nothing in the debug node.

**Comment by chughts** [comment]
The code is working as it should. I have verified this. I have a good understanding of what you are doing incorrectly, but  is a usage error, please raise a question on developerworks answers where I will be happy to answer the question.
