### ISSUE TITLE
Timeout for Conversation Node (and other nodes)

### ISSUE THREAD

**Issue by kenime** [watson-developer-cloud/node-red-node-watson#382]
I am considering adding a timeout parameter for conversation node such that if Watson cannot response after the configured period, the node will prompt error.

There are 2 ways to do so, either I use a process.env variable (such that it will be applicable to all watson nodes), or I only add it to the conversation node's v1.html (if other watson node wants to have such parameter they will have to add so to the html)

Any comment or suggestion which way I should opt for?

**Comment by chughts** [comment]
My preference would be to add it to the node configuration, defaulting to no timeout.

**Comment by jimbarnebee** [comment]
Suggestion -
Take a look at the code related to node-red-contrib-watson-ucg-custom:0.5.6 - i think it might have something useful as it is a extension of the Watson node with the timeout of the npm exposed.
 
 
 
 
 
----- Original message -----From: Soheel Chughtai <notifications@github.com>To: watson-developer-cloud/node-red-node-watson <node-red-node-watson@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [watson-developer-cloud/node-red-node-watson] Timeout for Conversation Node (and other nodes) (#382)Date: Wed, Feb 28, 2018 5:50 AM 
My preference would be to add it to the node configuration, defaulting to no timeout.

**Comment by chughts** [comment]
Implemented, waiting packaging into release

**Comment by chughts** [comment]
implemented only in Conversation node - released in 0.6.7
