### ISSUE TITLE
Migrate Nodes to use IAM Key

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-red-node-watson#411]
All new instances of the services are moving from username / password to use iam keys. All the nodes need to be updated. For bound services, simply the presence of a key and the absence of userid / password credentials should be enough. For unbound services, an extra key option may be needed.

Perhaps take the opportunity to move to credential configurations. 

This will need to be a version number bump.

**Comment by maclean-stu** [comment]
Any idea when this will be fixed. There are a lot of node red watson demos published on IBM sites for customers to play with that no longer work.

**Comment by chughts** [comment]
This is test driven, ie. we are implementing updates for the services that we can generate iam keys and test out. So far we have updates for Assistant, Discovery, Natural Language Understanding, Personality Insights, Speech to Text, Text to Speech, Tone Analyzer and Visual Recognition. 

Only Natural Language Classifier and Translator remain.

The update, however, is on hold as there are two open issues with STT and the underlying SDK. Feel free to add urgency to these issues - https://github.com/watson-developer-cloud/node-sdk/issues/696 and https://github.com/watson-developer-cloud/node-sdk/issues/697

**Comment by chughts** [comment]
Language Translator updated with IAM keys. Leaving only Natural Language Classifier.

Release 0.7.0 contains all the IAM key updates so far.

**Comment by chughts** [comment]
Natural Language Classifier node is updated for IAM Key authentication. API documentation suggests that it will be released, although the instances that I create still use the userid / password combination. Regression testing will be needed when IAM Keys do get issued for NLC.

Will be in Release 0.7.4
