### ISSUE TITLE
SpeechToText: Cannot save node property "auto-connect"

### ISSUE THREAD

**Issue by Brenne** [watson-developer-cloud/node-red-node-watson#413]
Hi,
the Speech to Text node has following issue: I can't save the state of the checkbox "Attempt auto connect on connection close"
I checked the code and the property is missing when the node is registered.
I suppose adding `'auto-connect' :{value: false},` should fix the issue.
https://github.com/watson-developer-cloud/node-red-node-watson/blob/778ae0654579624feb57bb20082ed8929999ce85/services/speech_to_text/v1.html#L591

**Comment by chughts** [comment]
Good spot. The state is actually being saved, it is just lost when you reopen the configuration. 

This has been fixed, and will be in the next release either 0.6.15 or 0.7.0 when we have sorted out how to perform STT with IAM keys.

**Comment by chughts** [comment]
Released in V 0.7.0
