### ISSUE TITLE
Update Watson Assistant Node

### ISSUE THREAD

**Issue by stefanopog** [watson-developer-cloud/node-red-node-watson#425]
The "Try It" option in the Watson Assistant workspace already integrates:
- multiple TEXT options
- IMAGE option
- OPTIONS option

The APIs only give me back the FIRST "TEXT" option.
Would it be possible to align the NodeRed version to the behavior of the "Try It" ? 

Thanks
/Stefano

**Comment by stefanopog** [comment]
What is missing is the GENERIC attribute under OUTPUT

**Comment by chughts** [comment]
The update to default to the latest API version should be in the next release. I can't say when that will be as I need to find spare time to work through some low hanging fruit. It is, however, possible to use the latest version now, by setting by setting `msg.params.version` to ‘2018-07-10’

**Comment by stefanopog** [comment]
Yeah ! Thank you !

**Comment by chughts** [comment]
Fixed in 0.7.4
Awaiting test completion and release
