### ISSUE TITLE
Rename Conversation node to Assistant

### ISSUE THREAD

**Issue by johnwalicki** [watson-developer-cloud/node-red-node-watson#427]
The Conversation node should be renamed to Assistant to reflect the product naming.
https://console.bluemix.net/catalog/services/watson-assistant-formerly-conversation

**Comment by chughts** [comment]
The node has been called Assistant on the palette for a while now. 

Agree that the text in the README.md should be updated in line. 

For the node - this is a request to change the directory file path. Which is only ever seen by developers. If it can be done without breaking existing flows then it is a candidate for the next release.

**Comment by johnwalicki** [comment]
I posted an insignificantly minor Pull Request that renames the Watson Assistant node in README.md  See
https://github.com/watson-developer-cloud/node-red-node-watson/pull/428

Its pending a Code Contribution Agreement approval?

The node has been called Assistant on the palette for a while now.
This pull request just renames Conversation to Assistant in the README.md
No code changes, just a documentation change.

**Comment by chughts** [comment]
Pull request #428 has been accepted. Will roll-out in next release.
