### ISSUE TITLE
Assistant V2

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-red-node-watson#429]
Create a node for Assistant V2 API

**Comment by chughts** [comment]
V2 went GA on 9 Nov2018, which might drive the urgency of this requirement.

**Comment by dluna-tridenia** [comment]
Hi,
Can the customer_id param (x-watson-metadata request header) be added in this version of the Assistant?
https://console.bluemix.net/docs/services/conversation/logs.html#deleting-data

**Comment by chughts** [comment]
@dluna-tridenia The delete-data is a V1 method, so can't be added to the V2 node.

**Comment by chughts** [comment]
Implemented, will be released in 0.7.5
