### ISSUE TITLE
No KG backend found for specified collection ID

### ISSUE THREAD

**Issue by ndssilva** [watson-developer-cloud/node-red-node-watson#430]
Despite a collection being well enriched with a custom config, Disco can't find a KG backend and issues the error message below:

400
No KG backend found for specified collection ID 'collection ID'. Please ensure that necessary enrichments were added to enable KG. Ask an administrator for more details.

**Comment by chughts** [comment]
By Disco KG I guess you mean Discovery Knowledge Graph. The error appears to suggest a user error in constructing the custom collection. 

I am therefore, going to close this issue as a user error. I will reopen if you are able to run the equivalent API method  using cURL on the collection as is, without the same error, and continue to get the error when using the node-red node.  For reference the cURL API documentation can be found at:

https://www.ibm.com/watson/developercloud/discovery/api/v1/curl.html?curl#query-using-get
