### ISSUE TITLE
Classify a buffer image does not work

### ISSUE THREAD

**Issue by fmanclossi** [watson-developer-cloud/node-red-node-watson#436]
Hi,
I'm setup a node-red flow to demo Watson Visual recognition with students using web and TJBot, too.
I setup a new Visual Recognition Service on Dallas using new authentication.
I upgraded to last version of node-red-node-watson (and others, too).
I inserted credential (APIKEY) and configured my flow.

Everything works fine when node receive an URL as input (both classify and faces works).
When node receive a Buffer object of an image, only Faces works.

Attached are all my screenshot
![2018-11-13 11_56_28-node-red _ detect objects node](https://user-images.githubusercontent.com/6938526/48409514-52eb3380-e73c-11e8-9a33-d5b21a66ef81.jpg)
![2018-11-13 11_56_28-node-red _ detect faces node](https://user-images.githubusercontent.com/6938526/48409515-52eb3380-e73c-11e8-8177-5eb05ea8d381.jpg)
![2018-11-13 11_53_12-node-red _issue detect objects](https://user-images.githubusercontent.com/6938526/48409516-52eb3380-e73c-11e8-89d0-5c0459adbb70.jpg)
![2018-11-13 11_53_51-node-red _working detect faces](https://user-images.githubusercontent.com/6938526/48409518-52eb3380-e73c-11e8-80be-e6b91cd5268b.jpg)
![2018-11-13 11_54_34-node-red _ file in face](https://user-images.githubusercontent.com/6938526/48409519-5383ca00-e73c-11e8-9efc-60f8158062d7.jpg)
![2018-11-13 11_54_34-node-red _ file in objects](https://user-images.githubusercontent.com/6938526/48409520-5383ca00-e73c-11e8-8660-5444732474e8.jpg)

Any hint?

**Comment by chughts** [comment]
That faces works, but classify doesn't implies that the input is different in the classify. In this case I think that this is a usage problem. Please raise a question on https://developer.ibm.com/answers

When you raise the question on developer works answers, please indicate the error status / response you get with classify. Also state whether you have tried to `classify` on the face image.

I will leave this issue open, in the case it does turn out to be a bug in the node, but for now lets continue the question on https://developer.ibm.com/answers

**Comment by fmanclossi** [comment]
open question in Developer -> https://developer.ibm.com/answers/questions/480248/node-red-node-watson-classify-a-buffer-image-does.html

**Comment by chughts** [comment]
Closing as there has been no follow-up to the response to the question in DeveloperWorks since the 13th Nov.
