### ISSUE TITLE
Bump to SDK 4.0.x

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-red-node-watson#455]
Version 4.0.x of the watson-developer-cloud SDK is now available. To ensure concurrency, watson node-red nodes need to be updated to work with this version of the SDK. 

New features of the watson-developer-cloud services will only be exposed through the latest versions of the watson-developer-cloud SDK. 

Breaking changes in the SDK can be found - https://github.com/watson-developer-cloud/node-sdk/blob/master/UPGRADE-4.0.md

**Comment by chughts** [comment]
watson-developer-cloud is now ibm-watson
Need to update dependency, when move to 4.0.x dependancy.

**Comment by kenime** [comment]
Any update on this? SDK v5 is about to release and we are about 2 major version behind

**Comment by chughts** [comment]
No updates. Maintenance of this collection is an out of hours weekend project, and I haven't had any weekends free to sit down and tackle this one yet. 

As far as I can tell, the 4.x and 5.x bumps don't actually expose new functionality to the underlying services and only provide breaking changes that require rework in a lot of the nodes. 
As the nodes currently work, there is something to be said to continue to be working off a stable SDK.

**Comment by kenime** [comment]
Totally understand, and node red makes it harder (if not impossible) to
implement test cases (I am suffering from it as well)

**Comment by chughts** [comment]
Following nodes have been updated in 0.8.0 to ibm-watson 5.2.1 SDK
    - Tone Analyzer node.
    - Personality Insights node.
    - Visual Recognition V3 node
    - Text to Speech node
    - Text to Speech Corpus Builder node

**Comment by chughts** [comment]
Following nodes have been updated in 0.8.1 to ibm-watson 5.2.1 SDK
-Speech to Text node
- Speech to Text Corpus Builder node
- Natural Language Understanding node
- Natural Language Classifier node
- Language Identifier node
- Language Translator node
- Translator Util node

**Comment by chughts** [comment]
Following nodes have been updated in 0.8.2 to ibm-watson 5.2.1 SDK
 - Document Translator node
 - Discovery node
- Discovery Document Loader node
- Discovery Query Builder node
- Assistant V1 Workspace Manager node

**Comment by chughts** [comment]
Final nodes migrated in 0.9.0
