### ISSUE TITLE
Assistant V2 node deletes the Assistant context variables

### ISSUE THREAD

**Issue by filippotramonto** [watson-developer-cloud/node-red-node-watson#464]
The Assistant V2 node deletes the context variables previously defined in Watson Assistant.
For example if a context variable is defined in the Welcome node, at the start of of the chatbot application, the variable is valued. Then at the first user input another Assistant node is triggered and there the context variable should be still exists, instead the variable is not more present, it was deleted.
On the contrary the V1 Assistant node works correctly and the context variables persist.

**Comment by chughts** [comment]
If you are sending in the session id, then the context variables will be preserved.

**Comment by filippotramonto** [comment]
Ok, thanks. This behaviour on context variables depending on the presence of the seesion_id parameter is not explained in the info box.
