### ISSUE TITLE
Add support for Discovery V2

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-red-node-watson#465]

**Comment by PriyaChilongia** [comment]
Hello team, We need to look urgently into a customer concern raised yesterday while they failed to make a connection between Node-red and APIV2 instance. There are no specific nodes (in node-RED) to connect API V2 (which is necessary for the “Plus” plan). Can something be done regarding this issue? 
Thank you for your help.

**Comment by chughts** [comment]
Unfortunately, I don't have the time currently to do this, but I am happy to accept a pull request from the community.

**Comment by chughts** [comment]
added in 0.10.0
