### ISSUE TITLE
Response not received - no connection was made to the service

### ISSUE THREAD

**Issue by Danyhn** [watson-developer-cloud/node-red-node-watson#494]
Dear,

We are have receiving error logs from watson-conversation-v1 with this message: "Response not received - no connection was made to the service.". I looked for this message on this repository but I didn't found. Can you explain what this message means and why we are getting that?

Regards,
Daniel Neves

**Comment by chughts** [comment]
This is not a message that the Watson Assistant node generates. 

You mention `Watson-conversation-v1`. That node was long replaced by an Assistant-v1 and Assistant-v2 node. 

Please check that you are using `node-red-node-watson` current version `0.9.5` and not something else.
