### ISSUE TITLE
Speech to Text Transcription stops at pause

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-red-node-watson#85]
The speech to text transcription response stops at the first pause in the audio track.

**Comment by nfriedly** [comment]
BTW, this is the expected behavior of the service. Set `continuous: true` to keep transcribing.

**Comment by chughts** [comment]
We already have that setting.  I need to review the node code to verify that it is clean. If I can fix it then I will close this issue.

**Comment by nfriedly** [comment]
Aah, OK, cool.

**Comment by arlemi** [comment]
There's already an issue opened about this here:
https://github.com/watson-developer-cloud/node-red-labs/issues/142

I'll let you decide which one to close. 
FYI, I've been looking into the node-sdk code and the continuous parameter is allowed in there so this is not the problem, I need to set a custom header so the Watson team can investigate.

**Comment by chughts** [comment]
Issue is in the code and not the flow, so this the right place for the issue.

**Comment by chughts** [comment]
Fixed in #90 
The full transcription is a concatenation of all the alternatives in the returned result data set.
